# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f905e7b3bad38c8f6d2b1815d7dffbb9f49c670e3f7c0e0f127c0ef26dda1e109548f749c864be06a164d30fb5f390ab69e658d0bb8e4c02060e8562ca50bf94

test:
  secret_key_base: f5310c4d1ddd7cd38838f80b9321e0671436bad5aae224011dbad80b1bbada87ff75a0d58dba95116922055e780c7be84d25e0c4605ef00ace0e985ab31adc65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
